/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 79
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__pair_token1 = 1,
  anon_sym_COLON = 2,
  aux_sym__pair_token2 = 3,
  anon_sym_if = 4,
  anon_sym_run = 5,
  sym__ignored_bash = 6,
  anon_sym_DOLLAR_LBRACE_LBRACE = 7,
  anon_sym_RBRACE_RBRACE = 8,
  anon_sym_true = 9,
  anon_sym_false = 10,
  sym_null = 11,
  anon_sym_DOT = 12,
  sym__int = 13,
  anon_sym_DASH = 14,
  anon_sym_0x = 15,
  aux_sym__hex_token1 = 16,
  anon_sym_e = 17,
  anon_sym_SQUOTE = 18,
  sym_string_content = 19,
  sym_scape_sequence = 20,
  sym__format_scape = 21,
  sym__format_content = 22,
  anon_sym_LBRACE = 23,
  anon_sym_RBRACE = 24,
  sym_asterisk = 25,
  sym_identifier = 26,
  anon_sym_LBRACK = 27,
  anon_sym_RBRACK = 28,
  anon_sym_LPAREN = 29,
  anon_sym_RPAREN = 30,
  anon_sym_COMMA = 31,
  anon_sym_format = 32,
  sym_not = 33,
  sym_lt = 34,
  sym_le = 35,
  sym_gt = 36,
  sym_ge = 37,
  sym_eq = 38,
  sym_ne = 39,
  sym_and = 40,
  sym_or = 41,
  sym_source = 42,
  sym__pair = 43,
  sym__if_pair = 44,
  sym__run_pair = 45,
  sym__evaluation = 46,
  sym_expression = 47,
  sym_delimited_expression = 48,
  sym__literal = 49,
  sym_boolean = 50,
  sym__dot = 51,
  sym_number = 52,
  sym__float = 53,
  sym__hex = 54,
  sym__exp = 55,
  sym_string = 56,
  sym_format_string = 57,
  sym_format_variable = 58,
  sym_format_index = 59,
  sym_property_deref = 60,
  sym_context = 61,
  sym_property = 62,
  sym_index = 63,
  sym_function_call = 64,
  sym__function = 65,
  sym_arguments = 66,
  sym__argument = 67,
  sym__format_function = 68,
  sym__format_arguments = 69,
  sym_operator = 70,
  sym_logical_group = 71,
  aux_sym__pair_repeat1 = 72,
  aux_sym__run_pair_repeat1 = 73,
  aux_sym__evaluation_repeat1 = 74,
  aux_sym_expression_repeat1 = 75,
  aux_sym_string_repeat1 = 76,
  aux_sym_format_string_repeat1 = 77,
  aux_sym_arguments_repeat1 = 78,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__pair_token1] = "_pair_token1",
  [anon_sym_COLON] = ":",
  [aux_sym__pair_token2] = "_pair_token2",
  [anon_sym_if] = "if",
  [anon_sym_run] = "run",
  [sym__ignored_bash] = "_ignored_bash",
  [anon_sym_DOLLAR_LBRACE_LBRACE] = "${{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_DOT] = ".",
  [sym__int] = "_int",
  [anon_sym_DASH] = "-",
  [anon_sym_0x] = "0x",
  [aux_sym__hex_token1] = "_hex_token1",
  [anon_sym_e] = "e",
  [anon_sym_SQUOTE] = "'",
  [sym_string_content] = "string_content",
  [sym_scape_sequence] = "scape_sequence",
  [sym__format_scape] = "scape_sequence",
  [sym__format_content] = "string_content",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_asterisk] = "asterisk",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_format] = "identifier",
  [sym_not] = "not",
  [sym_lt] = "lt",
  [sym_le] = "le",
  [sym_gt] = "gt",
  [sym_ge] = "ge",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_source] = "source",
  [sym__pair] = "_pair",
  [sym__if_pair] = "_if_pair",
  [sym__run_pair] = "_run_pair",
  [sym__evaluation] = "_evaluation",
  [sym_expression] = "expression",
  [sym_delimited_expression] = "delimited_expression",
  [sym__literal] = "_literal",
  [sym_boolean] = "boolean",
  [sym__dot] = "_dot",
  [sym_number] = "number",
  [sym__float] = "_float",
  [sym__hex] = "_hex",
  [sym__exp] = "_exp",
  [sym_string] = "string",
  [sym_format_string] = "format_string",
  [sym_format_variable] = "format_variable",
  [sym_format_index] = "format_index",
  [sym_property_deref] = "property_deref",
  [sym_context] = "context",
  [sym_property] = "property",
  [sym_index] = "index",
  [sym_function_call] = "function_call",
  [sym__function] = "_function",
  [sym_arguments] = "arguments",
  [sym__argument] = "_argument",
  [sym__format_function] = "_format_function",
  [sym__format_arguments] = "arguments",
  [sym_operator] = "operator",
  [sym_logical_group] = "logical_group",
  [aux_sym__pair_repeat1] = "_pair_repeat1",
  [aux_sym__run_pair_repeat1] = "_run_pair_repeat1",
  [aux_sym__evaluation_repeat1] = "_evaluation_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_format_string_repeat1] = "format_string_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__pair_token1] = aux_sym__pair_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym__pair_token2] = aux_sym__pair_token2,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_run] = anon_sym_run,
  [sym__ignored_bash] = sym__ignored_bash,
  [anon_sym_DOLLAR_LBRACE_LBRACE] = anon_sym_DOLLAR_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym__int] = sym__int,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_0x] = anon_sym_0x,
  [aux_sym__hex_token1] = aux_sym__hex_token1,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_scape_sequence] = sym_scape_sequence,
  [sym__format_scape] = sym_scape_sequence,
  [sym__format_content] = sym_string_content,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_asterisk] = sym_asterisk,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_format] = sym_identifier,
  [sym_not] = sym_not,
  [sym_lt] = sym_lt,
  [sym_le] = sym_le,
  [sym_gt] = sym_gt,
  [sym_ge] = sym_ge,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_source] = sym_source,
  [sym__pair] = sym__pair,
  [sym__if_pair] = sym__if_pair,
  [sym__run_pair] = sym__run_pair,
  [sym__evaluation] = sym__evaluation,
  [sym_expression] = sym_expression,
  [sym_delimited_expression] = sym_delimited_expression,
  [sym__literal] = sym__literal,
  [sym_boolean] = sym_boolean,
  [sym__dot] = sym__dot,
  [sym_number] = sym_number,
  [sym__float] = sym__float,
  [sym__hex] = sym__hex,
  [sym__exp] = sym__exp,
  [sym_string] = sym_string,
  [sym_format_string] = sym_format_string,
  [sym_format_variable] = sym_format_variable,
  [sym_format_index] = sym_format_index,
  [sym_property_deref] = sym_property_deref,
  [sym_context] = sym_context,
  [sym_property] = sym_property,
  [sym_index] = sym_index,
  [sym_function_call] = sym_function_call,
  [sym__function] = sym__function,
  [sym_arguments] = sym_arguments,
  [sym__argument] = sym__argument,
  [sym__format_function] = sym__format_function,
  [sym__format_arguments] = sym_arguments,
  [sym_operator] = sym_operator,
  [sym_logical_group] = sym_logical_group,
  [aux_sym__pair_repeat1] = aux_sym__pair_repeat1,
  [aux_sym__run_pair_repeat1] = aux_sym__run_pair_repeat1,
  [aux_sym__evaluation_repeat1] = aux_sym__evaluation_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_format_string_repeat1] = aux_sym_format_string_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__pair_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__pair_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_run] = {
    .visible = true,
    .named = false,
  },
  [sym__ignored_bash] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOLLAR_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym__int] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__hex_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_scape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym__format_scape] = {
    .visible = true,
    .named = true,
  },
  [sym__format_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_asterisk] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_not] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_le] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_ge] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__pair] = {
    .visible = false,
    .named = true,
  },
  [sym__if_pair] = {
    .visible = false,
    .named = true,
  },
  [sym__run_pair] = {
    .visible = false,
    .named = true,
  },
  [sym__evaluation] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_delimited_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__dot] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym__hex] = {
    .visible = false,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym_format_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_format_index] = {
    .visible = true,
    .named = true,
  },
  [sym_property_deref] = {
    .visible = true,
    .named = true,
  },
  [sym_context] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__function] = {
    .visible = false,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym__format_function] = {
    .visible = false,
    .named = true,
  },
  [sym__format_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_group] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pair_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__run_pair_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__evaluation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_format_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_function = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_function] = "function",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 0, .inherited = true},
    {field_function, 0, .inherited = true},
  [2] =
    {field_function, 0},
  [3] =
    {field_arguments, 2},
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 10,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 30,
  [56] = 32,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 60,
  [62] = 54,
  [63] = 59,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 64,
  [68] = 31,
  [69] = 37,
  [70] = 40,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 87,
  [92] = 92,
  [93] = 93,
  [94] = 88,
  [95] = 95,
  [96] = 92,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 97,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 113,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 115,
  [124] = 124,
  [125] = 111,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 109,
        '$', 31,
        '&', 4,
        '\'', 72,
        '(', 103,
        ')', 104,
        '*', 85,
        ',', 105,
        '-', 67,
        '.', 64,
        '0', 65,
        ':', 47,
        '<', 110,
        '=', 11,
        '>', 112,
        '[', 101,
        ']', 102,
        'e', 70,
        'f', 12,
        'i', 16,
        'n', 28,
        'r', 26,
        't', 23,
        '{', 82,
        '|', 33,
        '}', 84,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(81);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 2:
      if (lookahead == '\r') ADVANCE(76);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '!', 108,
        '$', 31,
        '\'', 71,
        '(', 103,
        ')', 104,
        '-', 67,
        '0', 65,
        'f', 86,
        'n', 99,
        't', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(116);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(72);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(82);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(83);
      if (lookahead == '}') ADVANCE(35);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(115);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(114);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(50);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 29:
      if (lookahead == '{') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == '{') ADVANCE(56);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 31:
      if (lookahead == '{') ADVANCE(29);
      END_STATE();
    case 32:
      if (lookahead == '{') ADVANCE(30);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 33:
      if (lookahead == '|') ADVANCE(117);
      END_STATE();
    case 34:
      if (lookahead == '}') ADVANCE(57);
      END_STATE();
    case 35:
      if (lookahead == '}') ADVANCE(78);
      END_STATE();
    case 36:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      END_STATE();
    case 37:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 109,
        '$', 31,
        '&', 4,
        '\'', 71,
        '(', 103,
        ')', 104,
        '*', 85,
        ',', 105,
        '-', 67,
        '.', 64,
        '0', 65,
        ':', 47,
        '<', 110,
        '=', 11,
        '>', 112,
        '[', 101,
        ']', 102,
        'e', 70,
        'f', 12,
        'i', 16,
        'n', 28,
        'r', 26,
        't', 23,
        '{', 82,
        '|', 33,
        '}', 84,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 38:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 10,
        '&', 4,
        '\'', 71,
        '(', 103,
        ')', 104,
        ',', 105,
        '.', 64,
        '<', 110,
        '=', 11,
        '>', 112,
        '[', 101,
        ']', 102,
        'i', 43,
        'r', 45,
        '|', 33,
        '}', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 39:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 10,
        '&', 4,
        ')', 104,
        ',', 105,
        '<', 110,
        '=', 11,
        '>', 112,
        ']', 102,
        'e', 70,
        '|', 33,
        '}', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      END_STATE();
    case 40:
      if (eof) ADVANCE(42);
      if (lookahead == '$') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 41:
      if (eof) ADVANCE(42);
      if (lookahead == '$') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == 'f') ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == 'n') ADVANCE(53);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == 'u') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__pair_token2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym__pair_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_run);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_run);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__ignored_bash);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__ignored_bash);
      if (lookahead == '$') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE_LBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__int);
      if (lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__hex_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(78);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '\'') ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_scape_sequence);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__format_scape);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__format_content);
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(82);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__format_content);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__format_content);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(78);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_asterisk);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(90);
      if (lookahead == 'o') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(91);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(93);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(98);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(107);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(92);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_format);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_format);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_not);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_not);
      if (lookahead == '=') ADVANCE(115);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(111);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_le);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(113);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_ge);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_ne);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 38},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 38},
  [17] = {.lex_state = 38},
  [18] = {.lex_state = 38},
  [19] = {.lex_state = 38},
  [20] = {.lex_state = 38},
  [21] = {.lex_state = 38},
  [22] = {.lex_state = 38},
  [23] = {.lex_state = 38},
  [24] = {.lex_state = 38},
  [25] = {.lex_state = 38},
  [26] = {.lex_state = 38},
  [27] = {.lex_state = 38},
  [28] = {.lex_state = 38},
  [29] = {.lex_state = 38},
  [30] = {.lex_state = 38},
  [31] = {.lex_state = 39},
  [32] = {.lex_state = 38},
  [33] = {.lex_state = 38},
  [34] = {.lex_state = 38},
  [35] = {.lex_state = 38},
  [36] = {.lex_state = 38},
  [37] = {.lex_state = 39},
  [38] = {.lex_state = 38},
  [39] = {.lex_state = 38},
  [40] = {.lex_state = 39},
  [41] = {.lex_state = 38},
  [42] = {.lex_state = 38},
  [43] = {.lex_state = 38},
  [44] = {.lex_state = 38},
  [45] = {.lex_state = 38},
  [46] = {.lex_state = 38},
  [47] = {.lex_state = 38},
  [48] = {.lex_state = 38},
  [49] = {.lex_state = 38},
  [50] = {.lex_state = 38},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 38},
  [53] = {.lex_state = 38},
  [54] = {.lex_state = 38},
  [55] = {.lex_state = 38},
  [56] = {.lex_state = 38},
  [57] = {.lex_state = 38},
  [58] = {.lex_state = 38},
  [59] = {.lex_state = 38},
  [60] = {.lex_state = 38},
  [61] = {.lex_state = 38},
  [62] = {.lex_state = 38},
  [63] = {.lex_state = 38},
  [64] = {.lex_state = 38},
  [65] = {.lex_state = 38},
  [66] = {.lex_state = 38},
  [67] = {.lex_state = 38},
  [68] = {.lex_state = 39},
  [69] = {.lex_state = 39},
  [70] = {.lex_state = 39},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 8},
  [73] = {.lex_state = 8},
  [74] = {.lex_state = 8},
  [75] = {.lex_state = 40},
  [76] = {.lex_state = 40},
  [77] = {.lex_state = 41},
  [78] = {.lex_state = 41},
  [79] = {.lex_state = 8},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 41},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 38},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 40},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 40},
  [88] = {.lex_state = 40},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 41},
  [92] = {.lex_state = 41},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 41},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 40},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 9},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 9},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 36},
  [125] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_run] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__int] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_scape_sequence] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_asterisk] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_format] = ACTIONS(1),
    [sym_not] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_le] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_ge] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_ne] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(110),
    [sym__pair] = STATE(109),
    [sym__if_pair] = STATE(109),
    [sym__run_pair] = STATE(109),
    [aux_sym__pair_token1] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_run] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_RPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(29), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    STATE(89), 1,
      sym__argument,
    STATE(116), 1,
      sym_arguments,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(43), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [66] = 17,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(33), 1,
      sym_null,
    ACTIONS(35), 1,
      sym__int,
    ACTIONS(37), 1,
      anon_sym_DASH,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(69), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(112), 2,
      sym_expression,
      sym_delimited_expression,
    STATE(65), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [127] = 17,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(29), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    STATE(98), 1,
      sym__argument,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(43), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [187] = 16,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(39), 1,
      sym_null,
    ACTIONS(41), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(58), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [244] = 16,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(43), 1,
      sym_null,
    ACTIONS(45), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(54), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [301] = 16,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(35), 1,
      sym__int,
    ACTIONS(37), 1,
      anon_sym_DASH,
    ACTIONS(47), 1,
      sym_null,
    ACTIONS(49), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(69), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(42), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [358] = 16,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(47), 1,
      sym_null,
    ACTIONS(51), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(42), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [415] = 16,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(53), 1,
      sym_null,
    ACTIONS(55), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(62), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [472] = 15,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(57), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(67), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [526] = 15,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(59), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(52), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [580] = 15,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(35), 1,
      sym__int,
    ACTIONS(37), 1,
      anon_sym_DASH,
    ACTIONS(61), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(69), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(49), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [634] = 15,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(63), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(44), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [688] = 15,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(61), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(49), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [742] = 15,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(65), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(23), 1,
      sym__function,
    STATE(37), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(64), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [796] = 9,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_index,
    STATE(100), 1,
      sym_property_deref,
    STATE(104), 1,
      sym__dot,
    ACTIONS(75), 2,
      sym_lt,
      sym_gt,
    STATE(18), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(67), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [835] = 8,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    STATE(21), 1,
      sym_index,
    STATE(100), 1,
      sym_property_deref,
    STATE(104), 1,
      sym__dot,
    ACTIONS(79), 2,
      sym_lt,
      sym_gt,
    STATE(19), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(77), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [871] = 8,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    STATE(21), 1,
      sym_index,
    STATE(100), 1,
      sym_property_deref,
    STATE(104), 1,
      sym__dot,
    ACTIONS(83), 2,
      sym_lt,
      sym_gt,
    STATE(20), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(81), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [907] = 8,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    STATE(21), 1,
      sym_index,
    STATE(100), 1,
      sym_property_deref,
    STATE(104), 1,
      sym__dot,
    ACTIONS(87), 2,
      sym_lt,
      sym_gt,
    STATE(20), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(85), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [943] = 8,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    STATE(21), 1,
      sym_index,
    STATE(100), 1,
      sym_property_deref,
    STATE(104), 1,
      sym__dot,
    ACTIONS(97), 2,
      sym_lt,
      sym_gt,
    STATE(20), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(89), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [979] = 2,
    ACTIONS(101), 2,
      sym_lt,
      sym_gt,
    ACTIONS(99), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [998] = 2,
    ACTIONS(105), 2,
      sym_lt,
      sym_gt,
    ACTIONS(103), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1017] = 2,
    ACTIONS(105), 2,
      sym_lt,
      sym_gt,
    ACTIONS(103), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1036] = 2,
    ACTIONS(109), 2,
      sym_lt,
      sym_gt,
    ACTIONS(107), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1055] = 2,
    ACTIONS(113), 2,
      sym_lt,
      sym_gt,
    ACTIONS(111), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1074] = 2,
    ACTIONS(117), 2,
      sym_lt,
      sym_gt,
    ACTIONS(115), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1093] = 2,
    ACTIONS(121), 2,
      sym_lt,
      sym_gt,
    ACTIONS(119), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1112] = 2,
    ACTIONS(125), 2,
      sym_lt,
      sym_gt,
    ACTIONS(123), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1131] = 2,
    ACTIONS(129), 2,
      sym_lt,
      sym_gt,
    ACTIONS(127), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1150] = 4,
    ACTIONS(133), 1,
      anon_sym_DOT,
    STATE(115), 1,
      sym__dot,
    ACTIONS(135), 2,
      sym_lt,
      sym_gt,
    ACTIONS(131), 10,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1173] = 2,
    ACTIONS(139), 2,
      sym_lt,
      sym_gt,
    ACTIONS(137), 11,
      anon_sym_RBRACE_RBRACE,
      anon_sym_e,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1191] = 5,
    STATE(8), 1,
      sym_operator,
    STATE(32), 1,
      aux_sym_expression_repeat1,
    ACTIONS(143), 2,
      sym_lt,
      sym_gt,
    ACTIONS(141), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(146), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1215] = 2,
    ACTIONS(151), 2,
      sym_lt,
      sym_gt,
    ACTIONS(149), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1233] = 2,
    ACTIONS(155), 2,
      sym_lt,
      sym_gt,
    ACTIONS(153), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1251] = 2,
    ACTIONS(159), 2,
      sym_lt,
      sym_gt,
    ACTIONS(157), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1269] = 2,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(161), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1287] = 3,
    ACTIONS(165), 1,
      anon_sym_e,
    ACTIONS(135), 2,
      sym_lt,
      sym_gt,
    ACTIONS(131), 10,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1307] = 2,
    ACTIONS(135), 2,
      sym_lt,
      sym_gt,
    ACTIONS(131), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1325] = 2,
    ACTIONS(169), 2,
      sym_lt,
      sym_gt,
    ACTIONS(167), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1343] = 2,
    ACTIONS(173), 2,
      sym_lt,
      sym_gt,
    ACTIONS(171), 11,
      anon_sym_RBRACE_RBRACE,
      anon_sym_e,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1361] = 2,
    ACTIONS(177), 2,
      sym_lt,
      sym_gt,
    ACTIONS(175), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1378] = 2,
    ACTIONS(179), 2,
      sym_lt,
      sym_gt,
    ACTIONS(141), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1395] = 5,
    STATE(8), 1,
      sym_operator,
    STATE(48), 1,
      aux_sym_expression_repeat1,
    ACTIONS(181), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1418] = 5,
    STATE(8), 1,
      sym_operator,
    STATE(46), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(187), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1441] = 2,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(189), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1458] = 5,
    STATE(8), 1,
      sym_operator,
    STATE(32), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1481] = 2,
    ACTIONS(197), 2,
      sym_lt,
      sym_gt,
    ACTIONS(195), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1498] = 5,
    STATE(8), 1,
      sym_operator,
    STATE(32), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(187), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1521] = 2,
    ACTIONS(201), 2,
      sym_lt,
      sym_gt,
    ACTIONS(199), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1538] = 2,
    ACTIONS(205), 2,
      sym_lt,
      sym_gt,
    ACTIONS(203), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1555] = 2,
    ACTIONS(209), 5,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_SQUOTE,
      anon_sym_LPAREN,
      sym_not,
    ACTIONS(207), 6,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__int,
      sym_identifier,
      anon_sym_format,
  [1571] = 5,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_operator,
    STATE(57), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1593] = 5,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_operator,
    STATE(32), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1615] = 5,
    ACTIONS(213), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(8), 1,
      sym_operator,
    STATE(60), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1637] = 4,
    ACTIONS(215), 1,
      anon_sym_DOT,
    STATE(123), 1,
      sym__dot,
    ACTIONS(135), 2,
      sym_lt,
      sym_gt,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1657] = 5,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_operator,
    STATE(56), 1,
      aux_sym_expression_repeat1,
    ACTIONS(143), 2,
      sym_lt,
      sym_gt,
    ACTIONS(146), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1679] = 5,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_operator,
    STATE(32), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1701] = 5,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_operator,
    STATE(53), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1723] = 5,
    ACTIONS(221), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(8), 1,
      sym_operator,
    STATE(32), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1745] = 5,
    ACTIONS(223), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(8), 1,
      sym_operator,
    STATE(32), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1767] = 5,
    ACTIONS(225), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(8), 1,
      sym_operator,
    STATE(32), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1789] = 5,
    ACTIONS(227), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(8), 1,
      sym_operator,
    STATE(61), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1811] = 5,
    ACTIONS(229), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(8), 1,
      sym_operator,
    STATE(32), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1833] = 5,
    ACTIONS(225), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(8), 1,
      sym_operator,
    STATE(63), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1855] = 5,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_operator,
    STATE(66), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1877] = 5,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_operator,
    STATE(56), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1899] = 5,
    ACTIONS(223), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(8), 1,
      sym_operator,
    STATE(59), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(185), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1921] = 2,
    ACTIONS(139), 2,
      sym_lt,
      sym_gt,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      anon_sym_e,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1936] = 3,
    ACTIONS(165), 1,
      anon_sym_e,
    ACTIONS(135), 2,
      sym_lt,
      sym_gt,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1953] = 2,
    ACTIONS(173), 2,
      sym_lt,
      sym_gt,
    ACTIONS(171), 8,
      ts_builtin_sym_end,
      anon_sym_e,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1968] = 7,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(37), 1,
      sym__float,
    STATE(38), 2,
      sym__hex,
      sym__exp,
    STATE(122), 2,
      sym_number,
      sym_string,
  [1992] = 5,
    ACTIONS(235), 1,
      anon_sym_SQUOTE,
    ACTIONS(237), 1,
      sym__format_scape,
    ACTIONS(239), 1,
      sym__format_content,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    STATE(73), 2,
      sym_format_variable,
      aux_sym_format_string_repeat1,
  [2009] = 5,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    ACTIONS(243), 1,
      anon_sym_SQUOTE,
    ACTIONS(245), 1,
      sym__format_scape,
    ACTIONS(247), 1,
      sym__format_content,
    STATE(74), 2,
      sym_format_variable,
      aux_sym_format_string_repeat1,
  [2026] = 5,
    ACTIONS(249), 1,
      anon_sym_SQUOTE,
    ACTIONS(251), 1,
      sym__format_scape,
    ACTIONS(254), 1,
      sym__format_content,
    ACTIONS(257), 1,
      anon_sym_LBRACE,
    STATE(74), 2,
      sym_format_variable,
      aux_sym_format_string_repeat1,
  [2043] = 4,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
    ACTIONS(262), 1,
      aux_sym__pair_token2,
    ACTIONS(264), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(76), 2,
      sym_delimited_expression,
      aux_sym__pair_repeat1,
  [2057] = 4,
    ACTIONS(266), 1,
      ts_builtin_sym_end,
    ACTIONS(268), 1,
      aux_sym__pair_token2,
    ACTIONS(271), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(76), 2,
      sym_delimited_expression,
      aux_sym__pair_repeat1,
  [2071] = 4,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
    ACTIONS(276), 1,
      sym__ignored_bash,
    ACTIONS(278), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(78), 2,
      sym_delimited_expression,
      aux_sym__run_pair_repeat1,
  [2085] = 4,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
    ACTIONS(282), 1,
      sym__ignored_bash,
    ACTIONS(285), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(78), 2,
      sym_delimited_expression,
      aux_sym__run_pair_repeat1,
  [2099] = 2,
    ACTIONS(290), 1,
      sym__format_scape,
    ACTIONS(288), 3,
      anon_sym_SQUOTE,
      sym__format_content,
      anon_sym_LBRACE,
  [2108] = 4,
    ACTIONS(292), 1,
      anon_sym_SQUOTE,
    ACTIONS(294), 1,
      sym_string_content,
    ACTIONS(297), 1,
      sym_scape_sequence,
    STATE(80), 1,
      aux_sym_string_repeat1,
  [2121] = 3,
    ACTIONS(278), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(300), 1,
      sym__ignored_bash,
    STATE(77), 2,
      sym_delimited_expression,
      aux_sym__run_pair_repeat1,
  [2132] = 4,
    ACTIONS(302), 1,
      anon_sym_SQUOTE,
    ACTIONS(304), 1,
      sym_string_content,
    ACTIONS(306), 1,
      sym_scape_sequence,
    STATE(80), 1,
      aux_sym_string_repeat1,
  [2145] = 4,
    ACTIONS(308), 1,
      anon_sym_SQUOTE,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      sym_format_string,
    STATE(119), 1,
      sym__format_arguments,
  [2158] = 4,
    ACTIONS(312), 1,
      anon_sym_SQUOTE,
    ACTIONS(314), 1,
      sym_string_content,
    ACTIONS(316), 1,
      sym_scape_sequence,
    STATE(82), 1,
      aux_sym_string_repeat1,
  [2171] = 3,
    ACTIONS(264), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(318), 1,
      aux_sym__pair_token2,
    STATE(75), 2,
      sym_delimited_expression,
      aux_sym__pair_repeat1,
  [2182] = 3,
    ACTIONS(320), 1,
      anon_sym_RPAREN,
    ACTIONS(322), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym_arguments_repeat1,
  [2192] = 2,
    ACTIONS(326), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(324), 2,
      ts_builtin_sym_end,
      aux_sym__pair_token2,
  [2200] = 2,
    ACTIONS(330), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(328), 2,
      ts_builtin_sym_end,
      aux_sym__pair_token2,
  [2208] = 3,
    ACTIONS(322), 1,
      anon_sym_COMMA,
    ACTIONS(332), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_arguments_repeat1,
  [2218] = 3,
    ACTIONS(334), 1,
      anon_sym_RPAREN,
    ACTIONS(336), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym_arguments_repeat1,
  [2228] = 2,
    ACTIONS(326), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(324), 2,
      ts_builtin_sym_end,
      sym__ignored_bash,
  [2236] = 2,
    ACTIONS(341), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(339), 2,
      ts_builtin_sym_end,
      sym__ignored_bash,
  [2244] = 3,
    ACTIONS(322), 1,
      anon_sym_COMMA,
    ACTIONS(343), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_arguments_repeat1,
  [2254] = 2,
    ACTIONS(330), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(328), 2,
      ts_builtin_sym_end,
      sym__ignored_bash,
  [2262] = 3,
    ACTIONS(322), 1,
      anon_sym_COMMA,
    ACTIONS(345), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_arguments_repeat1,
  [2272] = 2,
    ACTIONS(341), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(339), 2,
      ts_builtin_sym_end,
      aux_sym__pair_token2,
  [2280] = 2,
    ACTIONS(347), 1,
      anon_sym_DOT,
    STATE(113), 1,
      sym__dot,
  [2287] = 1,
    ACTIONS(334), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2292] = 1,
    ACTIONS(349), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2297] = 1,
    ACTIONS(351), 2,
      sym_asterisk,
      sym_identifier,
  [2302] = 2,
    ACTIONS(353), 1,
      sym__int,
    STATE(108), 1,
      sym_format_index,
  [2309] = 1,
    ACTIONS(355), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2314] = 2,
    ACTIONS(357), 1,
      anon_sym_DOT,
    STATE(117), 1,
      sym__dot,
  [2321] = 1,
    ACTIONS(359), 2,
      sym_asterisk,
      sym_identifier,
  [2326] = 2,
    ACTIONS(361), 1,
      sym__int,
    ACTIONS(363), 1,
      anon_sym_DASH,
  [2333] = 1,
    ACTIONS(365), 1,
      anon_sym_RBRACE,
  [2337] = 1,
    ACTIONS(367), 1,
      anon_sym_COLON,
  [2341] = 1,
    ACTIONS(369), 1,
      anon_sym_RBRACE,
  [2345] = 1,
    ACTIONS(371), 1,
      ts_builtin_sym_end,
  [2349] = 1,
    ACTIONS(373), 1,
      ts_builtin_sym_end,
  [2353] = 1,
    ACTIONS(375), 1,
      sym__int,
  [2357] = 1,
    ACTIONS(377), 1,
      ts_builtin_sym_end,
  [2361] = 1,
    ACTIONS(379), 1,
      sym__int,
  [2365] = 1,
    ACTIONS(381), 1,
      anon_sym_COLON,
  [2369] = 1,
    ACTIONS(383), 1,
      sym__int,
  [2373] = 1,
    ACTIONS(385), 1,
      anon_sym_RPAREN,
  [2377] = 1,
    ACTIONS(387), 1,
      sym__int,
  [2381] = 1,
    ACTIONS(389), 1,
      anon_sym_LPAREN,
  [2385] = 1,
    ACTIONS(391), 1,
      anon_sym_RPAREN,
  [2389] = 1,
    ACTIONS(393), 1,
      anon_sym_COLON,
  [2393] = 1,
    ACTIONS(395), 1,
      sym__int,
  [2397] = 1,
    ACTIONS(397), 1,
      anon_sym_RBRACK,
  [2401] = 1,
    ACTIONS(399), 1,
      sym__int,
  [2405] = 1,
    ACTIONS(401), 1,
      aux_sym__hex_token1,
  [2409] = 1,
    ACTIONS(403), 1,
      sym__int,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 66,
  [SMALL_STATE(4)] = 127,
  [SMALL_STATE(5)] = 187,
  [SMALL_STATE(6)] = 244,
  [SMALL_STATE(7)] = 301,
  [SMALL_STATE(8)] = 358,
  [SMALL_STATE(9)] = 415,
  [SMALL_STATE(10)] = 472,
  [SMALL_STATE(11)] = 526,
  [SMALL_STATE(12)] = 580,
  [SMALL_STATE(13)] = 634,
  [SMALL_STATE(14)] = 688,
  [SMALL_STATE(15)] = 742,
  [SMALL_STATE(16)] = 796,
  [SMALL_STATE(17)] = 835,
  [SMALL_STATE(18)] = 871,
  [SMALL_STATE(19)] = 907,
  [SMALL_STATE(20)] = 943,
  [SMALL_STATE(21)] = 979,
  [SMALL_STATE(22)] = 998,
  [SMALL_STATE(23)] = 1017,
  [SMALL_STATE(24)] = 1036,
  [SMALL_STATE(25)] = 1055,
  [SMALL_STATE(26)] = 1074,
  [SMALL_STATE(27)] = 1093,
  [SMALL_STATE(28)] = 1112,
  [SMALL_STATE(29)] = 1131,
  [SMALL_STATE(30)] = 1150,
  [SMALL_STATE(31)] = 1173,
  [SMALL_STATE(32)] = 1191,
  [SMALL_STATE(33)] = 1215,
  [SMALL_STATE(34)] = 1233,
  [SMALL_STATE(35)] = 1251,
  [SMALL_STATE(36)] = 1269,
  [SMALL_STATE(37)] = 1287,
  [SMALL_STATE(38)] = 1307,
  [SMALL_STATE(39)] = 1325,
  [SMALL_STATE(40)] = 1343,
  [SMALL_STATE(41)] = 1361,
  [SMALL_STATE(42)] = 1378,
  [SMALL_STATE(43)] = 1395,
  [SMALL_STATE(44)] = 1418,
  [SMALL_STATE(45)] = 1441,
  [SMALL_STATE(46)] = 1458,
  [SMALL_STATE(47)] = 1481,
  [SMALL_STATE(48)] = 1498,
  [SMALL_STATE(49)] = 1521,
  [SMALL_STATE(50)] = 1538,
  [SMALL_STATE(51)] = 1555,
  [SMALL_STATE(52)] = 1571,
  [SMALL_STATE(53)] = 1593,
  [SMALL_STATE(54)] = 1615,
  [SMALL_STATE(55)] = 1637,
  [SMALL_STATE(56)] = 1657,
  [SMALL_STATE(57)] = 1679,
  [SMALL_STATE(58)] = 1701,
  [SMALL_STATE(59)] = 1723,
  [SMALL_STATE(60)] = 1745,
  [SMALL_STATE(61)] = 1767,
  [SMALL_STATE(62)] = 1789,
  [SMALL_STATE(63)] = 1811,
  [SMALL_STATE(64)] = 1833,
  [SMALL_STATE(65)] = 1855,
  [SMALL_STATE(66)] = 1877,
  [SMALL_STATE(67)] = 1899,
  [SMALL_STATE(68)] = 1921,
  [SMALL_STATE(69)] = 1936,
  [SMALL_STATE(70)] = 1953,
  [SMALL_STATE(71)] = 1968,
  [SMALL_STATE(72)] = 1992,
  [SMALL_STATE(73)] = 2009,
  [SMALL_STATE(74)] = 2026,
  [SMALL_STATE(75)] = 2043,
  [SMALL_STATE(76)] = 2057,
  [SMALL_STATE(77)] = 2071,
  [SMALL_STATE(78)] = 2085,
  [SMALL_STATE(79)] = 2099,
  [SMALL_STATE(80)] = 2108,
  [SMALL_STATE(81)] = 2121,
  [SMALL_STATE(82)] = 2132,
  [SMALL_STATE(83)] = 2145,
  [SMALL_STATE(84)] = 2158,
  [SMALL_STATE(85)] = 2171,
  [SMALL_STATE(86)] = 2182,
  [SMALL_STATE(87)] = 2192,
  [SMALL_STATE(88)] = 2200,
  [SMALL_STATE(89)] = 2208,
  [SMALL_STATE(90)] = 2218,
  [SMALL_STATE(91)] = 2228,
  [SMALL_STATE(92)] = 2236,
  [SMALL_STATE(93)] = 2244,
  [SMALL_STATE(94)] = 2254,
  [SMALL_STATE(95)] = 2262,
  [SMALL_STATE(96)] = 2272,
  [SMALL_STATE(97)] = 2280,
  [SMALL_STATE(98)] = 2287,
  [SMALL_STATE(99)] = 2292,
  [SMALL_STATE(100)] = 2297,
  [SMALL_STATE(101)] = 2302,
  [SMALL_STATE(102)] = 2309,
  [SMALL_STATE(103)] = 2314,
  [SMALL_STATE(104)] = 2321,
  [SMALL_STATE(105)] = 2326,
  [SMALL_STATE(106)] = 2333,
  [SMALL_STATE(107)] = 2337,
  [SMALL_STATE(108)] = 2341,
  [SMALL_STATE(109)] = 2345,
  [SMALL_STATE(110)] = 2349,
  [SMALL_STATE(111)] = 2353,
  [SMALL_STATE(112)] = 2357,
  [SMALL_STATE(113)] = 2361,
  [SMALL_STATE(114)] = 2365,
  [SMALL_STATE(115)] = 2369,
  [SMALL_STATE(116)] = 2373,
  [SMALL_STATE(117)] = 2377,
  [SMALL_STATE(118)] = 2381,
  [SMALL_STATE(119)] = 2385,
  [SMALL_STATE(120)] = 2389,
  [SMALL_STATE(121)] = 2393,
  [SMALL_STATE(122)] = 2397,
  [SMALL_STATE(123)] = 2401,
  [SMALL_STATE(124)] = 2405,
  [SMALL_STATE(125)] = 2409,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__evaluation, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__evaluation, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__evaluation, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__evaluation, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__evaluation_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__evaluation_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__evaluation_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__evaluation_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 1, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 1, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function, 3, 0, 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__function, 3, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function, 4, 0, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__function, 4, 0, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_function, 3, 0, 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__format_function, 3, 0, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_function, 4, 0, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__format_function, 4, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__hex, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_group, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_group, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_group, 4, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_group, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_group, 5, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_group, 5, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [257] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pair, 3, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pair_repeat1, 2, 0, 0),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pair_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [271] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pair_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__run_pair, 3, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [278] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__run_pair_repeat1, 2, 0, 0),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__run_pair_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [285] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__run_pair_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format_variable, 3, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_variable, 3, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [294] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [304] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [312] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [314] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimited_expression, 3, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimited_expression, 3, 0, 0),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimited_expression, 5, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimited_expression, 5, 0, 0),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [336] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimited_expression, 4, 0, 0),
  [341] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimited_expression, 4, 0, 0),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_arguments, 2, 0, 0),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_arguments, 1, 0, 0),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 2, 0, 0),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 3, 0, 0),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_deref, 1, 0, 0),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_index, 1, 0, 0),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [373] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [377] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__if_pair, 3, 0, 0),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gh_actions_expressions(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gh_actions_expressions",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 5,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
