/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 121
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 78
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__pair_token1 = 1,
  anon_sym_COLON = 2,
  aux_sym__pair_token2 = 3,
  anon_sym_if = 4,
  anon_sym_run = 5,
  sym__ignored_bash = 6,
  anon_sym_DOLLAR_LBRACE_LBRACE = 7,
  anon_sym_RBRACE_RBRACE = 8,
  anon_sym_true = 9,
  anon_sym_false = 10,
  sym_null = 11,
  anon_sym_DOT = 12,
  sym__int = 13,
  anon_sym_DASH = 14,
  anon_sym_0x = 15,
  aux_sym__hex_token1 = 16,
  anon_sym_e = 17,
  anon_sym_SQUOTE = 18,
  sym_string_content = 19,
  sym_scape_sequence = 20,
  sym__format_scape = 21,
  sym__format_content = 22,
  anon_sym_LBRACE = 23,
  anon_sym_RBRACE = 24,
  sym_asterisk = 25,
  sym_identifier = 26,
  anon_sym_LBRACK = 27,
  anon_sym_RBRACK = 28,
  anon_sym_LPAREN = 29,
  anon_sym_RPAREN = 30,
  anon_sym_COMMA = 31,
  anon_sym_format = 32,
  sym_not = 33,
  sym_lt = 34,
  sym_le = 35,
  sym_gt = 36,
  sym_ge = 37,
  sym_eq = 38,
  sym_ne = 39,
  sym_and = 40,
  sym_or = 41,
  sym_source = 42,
  sym__pair = 43,
  sym__if_pair = 44,
  sym__run_pair = 45,
  sym__evaluation = 46,
  sym_expression = 47,
  sym_delimited_expression = 48,
  sym__literal = 49,
  sym_boolean = 50,
  sym__dot = 51,
  sym_number = 52,
  sym__float = 53,
  sym__hex = 54,
  sym__exp = 55,
  sym_string = 56,
  sym_format_string = 57,
  sym_format_variable = 58,
  sym_format_index = 59,
  sym_property_deref = 60,
  sym_context = 61,
  sym_property = 62,
  sym_index = 63,
  sym_function_call = 64,
  sym__function = 65,
  sym_arguments = 66,
  sym__format_function = 67,
  sym__format_arguments = 68,
  sym_operator = 69,
  sym_logical_group = 70,
  aux_sym__pair_repeat1 = 71,
  aux_sym__run_pair_repeat1 = 72,
  aux_sym__evaluation_repeat1 = 73,
  aux_sym_expression_repeat1 = 74,
  aux_sym_string_repeat1 = 75,
  aux_sym_format_string_repeat1 = 76,
  aux_sym_arguments_repeat1 = 77,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__pair_token1] = "_pair_token1",
  [anon_sym_COLON] = ":",
  [aux_sym__pair_token2] = "_pair_token2",
  [anon_sym_if] = "if",
  [anon_sym_run] = "run",
  [sym__ignored_bash] = "_ignored_bash",
  [anon_sym_DOLLAR_LBRACE_LBRACE] = "${{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_DOT] = ".",
  [sym__int] = "_int",
  [anon_sym_DASH] = "-",
  [anon_sym_0x] = "0x",
  [aux_sym__hex_token1] = "_hex_token1",
  [anon_sym_e] = "e",
  [anon_sym_SQUOTE] = "'",
  [sym_string_content] = "string_content",
  [sym_scape_sequence] = "scape_sequence",
  [sym__format_scape] = "scape_sequence",
  [sym__format_content] = "string_content",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_asterisk] = "asterisk",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_format] = "identifier",
  [sym_not] = "not",
  [sym_lt] = "lt",
  [sym_le] = "le",
  [sym_gt] = "gt",
  [sym_ge] = "ge",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_source] = "source",
  [sym__pair] = "_pair",
  [sym__if_pair] = "_if_pair",
  [sym__run_pair] = "_run_pair",
  [sym__evaluation] = "_evaluation",
  [sym_expression] = "expression",
  [sym_delimited_expression] = "delimited_expression",
  [sym__literal] = "_literal",
  [sym_boolean] = "boolean",
  [sym__dot] = "_dot",
  [sym_number] = "number",
  [sym__float] = "_float",
  [sym__hex] = "_hex",
  [sym__exp] = "_exp",
  [sym_string] = "string",
  [sym_format_string] = "format_string",
  [sym_format_variable] = "format_variable",
  [sym_format_index] = "format_index",
  [sym_property_deref] = "property_deref",
  [sym_context] = "context",
  [sym_property] = "property",
  [sym_index] = "index",
  [sym_function_call] = "function_call",
  [sym__function] = "_function",
  [sym_arguments] = "arguments",
  [sym__format_function] = "_format_function",
  [sym__format_arguments] = "arguments",
  [sym_operator] = "operator",
  [sym_logical_group] = "logical_group",
  [aux_sym__pair_repeat1] = "_pair_repeat1",
  [aux_sym__run_pair_repeat1] = "_run_pair_repeat1",
  [aux_sym__evaluation_repeat1] = "_evaluation_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_format_string_repeat1] = "format_string_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__pair_token1] = aux_sym__pair_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym__pair_token2] = aux_sym__pair_token2,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_run] = anon_sym_run,
  [sym__ignored_bash] = sym__ignored_bash,
  [anon_sym_DOLLAR_LBRACE_LBRACE] = anon_sym_DOLLAR_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym__int] = sym__int,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_0x] = anon_sym_0x,
  [aux_sym__hex_token1] = aux_sym__hex_token1,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_scape_sequence] = sym_scape_sequence,
  [sym__format_scape] = sym_scape_sequence,
  [sym__format_content] = sym_string_content,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_asterisk] = sym_asterisk,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_format] = sym_identifier,
  [sym_not] = sym_not,
  [sym_lt] = sym_lt,
  [sym_le] = sym_le,
  [sym_gt] = sym_gt,
  [sym_ge] = sym_ge,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_source] = sym_source,
  [sym__pair] = sym__pair,
  [sym__if_pair] = sym__if_pair,
  [sym__run_pair] = sym__run_pair,
  [sym__evaluation] = sym__evaluation,
  [sym_expression] = sym_expression,
  [sym_delimited_expression] = sym_delimited_expression,
  [sym__literal] = sym__literal,
  [sym_boolean] = sym_boolean,
  [sym__dot] = sym__dot,
  [sym_number] = sym_number,
  [sym__float] = sym__float,
  [sym__hex] = sym__hex,
  [sym__exp] = sym__exp,
  [sym_string] = sym_string,
  [sym_format_string] = sym_format_string,
  [sym_format_variable] = sym_format_variable,
  [sym_format_index] = sym_format_index,
  [sym_property_deref] = sym_property_deref,
  [sym_context] = sym_context,
  [sym_property] = sym_property,
  [sym_index] = sym_index,
  [sym_function_call] = sym_function_call,
  [sym__function] = sym__function,
  [sym_arguments] = sym_arguments,
  [sym__format_function] = sym__format_function,
  [sym__format_arguments] = sym_arguments,
  [sym_operator] = sym_operator,
  [sym_logical_group] = sym_logical_group,
  [aux_sym__pair_repeat1] = aux_sym__pair_repeat1,
  [aux_sym__run_pair_repeat1] = aux_sym__run_pair_repeat1,
  [aux_sym__evaluation_repeat1] = aux_sym__evaluation_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_format_string_repeat1] = aux_sym_format_string_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__pair_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__pair_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_run] = {
    .visible = true,
    .named = false,
  },
  [sym__ignored_bash] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOLLAR_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym__int] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__hex_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_scape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym__format_scape] = {
    .visible = true,
    .named = true,
  },
  [sym__format_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_asterisk] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_not] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_le] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_ge] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__pair] = {
    .visible = false,
    .named = true,
  },
  [sym__if_pair] = {
    .visible = false,
    .named = true,
  },
  [sym__run_pair] = {
    .visible = false,
    .named = true,
  },
  [sym__evaluation] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_delimited_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__dot] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym__hex] = {
    .visible = false,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym_format_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_format_index] = {
    .visible = true,
    .named = true,
  },
  [sym_property_deref] = {
    .visible = true,
    .named = true,
  },
  [sym_context] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__function] = {
    .visible = false,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__format_function] = {
    .visible = false,
    .named = true,
  },
  [sym__format_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_group] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pair_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__run_pair_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__evaluation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_format_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_function = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_function] = "function",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 0, .inherited = true},
    {field_function, 0, .inherited = true},
  [2] =
    {field_function, 0},
  [3] =
    {field_arguments, 2},
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 10,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 29,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 47,
  [56] = 56,
  [57] = 54,
  [58] = 45,
  [59] = 59,
  [60] = 60,
  [61] = 43,
  [62] = 44,
  [63] = 32,
  [64] = 33,
  [65] = 35,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 84,
  [88] = 86,
  [89] = 81,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 98,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 107,
  [114] = 114,
  [115] = 115,
  [116] = 109,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 110,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 109,
        '$', 31,
        '&', 4,
        '\'', 72,
        '(', 103,
        ')', 104,
        '*', 85,
        ',', 105,
        '-', 67,
        '.', 64,
        '0', 65,
        ':', 47,
        '<', 110,
        '=', 11,
        '>', 112,
        '[', 101,
        ']', 102,
        'e', 70,
        'f', 12,
        'i', 16,
        'n', 28,
        'r', 26,
        't', 23,
        '{', 82,
        '|', 33,
        '}', 84,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(81);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 2:
      if (lookahead == '\r') ADVANCE(76);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '!', 108,
        '$', 31,
        '\'', 71,
        '(', 103,
        ')', 104,
        '-', 67,
        '0', 65,
        'f', 86,
        'n', 99,
        't', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(116);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(72);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(82);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(83);
      if (lookahead == '}') ADVANCE(35);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(115);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(114);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 16:
      if (lookahead == 'f') ADVANCE(50);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 29:
      if (lookahead == '{') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == '{') ADVANCE(56);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 31:
      if (lookahead == '{') ADVANCE(29);
      END_STATE();
    case 32:
      if (lookahead == '{') ADVANCE(30);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 33:
      if (lookahead == '|') ADVANCE(117);
      END_STATE();
    case 34:
      if (lookahead == '}') ADVANCE(57);
      END_STATE();
    case 35:
      if (lookahead == '}') ADVANCE(78);
      END_STATE();
    case 36:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      END_STATE();
    case 37:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 109,
        '$', 31,
        '&', 4,
        '\'', 71,
        '(', 103,
        ')', 104,
        '*', 85,
        ',', 105,
        '-', 67,
        '.', 64,
        '0', 65,
        ':', 47,
        '<', 110,
        '=', 11,
        '>', 112,
        '[', 101,
        ']', 102,
        'e', 70,
        'f', 12,
        'i', 16,
        'n', 28,
        'r', 26,
        't', 23,
        '{', 82,
        '|', 33,
        '}', 84,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 38:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 10,
        '&', 4,
        '\'', 71,
        '(', 103,
        ')', 104,
        ',', 105,
        '.', 64,
        '<', 110,
        '=', 11,
        '>', 112,
        '[', 101,
        ']', 102,
        'i', 43,
        'r', 45,
        '|', 33,
        '}', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 39:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 10,
        '&', 4,
        ')', 104,
        ',', 105,
        '<', 110,
        '=', 11,
        '>', 112,
        ']', 102,
        'e', 70,
        '|', 33,
        '}', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      END_STATE();
    case 40:
      if (eof) ADVANCE(42);
      if (lookahead == '$') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 41:
      if (eof) ADVANCE(42);
      if (lookahead == '$') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == 'f') ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == 'n') ADVANCE(53);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == 'u') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__pair_token2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym__pair_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_run);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_run);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__ignored_bash);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__ignored_bash);
      if (lookahead == '$') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE_LBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__int);
      if (lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__hex_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(78);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '\'') ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_scape_sequence);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__format_scape);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__format_content);
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(82);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__format_content);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__format_content);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(78);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_asterisk);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(90);
      if (lookahead == 'o') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(91);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(93);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(98);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(107);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(92);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_format);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_format);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_not);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_not);
      if (lookahead == '=') ADVANCE(115);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(111);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_le);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(113);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_ge);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_ne);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 38},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 38},
  [16] = {.lex_state = 38},
  [17] = {.lex_state = 38},
  [18] = {.lex_state = 38},
  [19] = {.lex_state = 38},
  [20] = {.lex_state = 38},
  [21] = {.lex_state = 38},
  [22] = {.lex_state = 38},
  [23] = {.lex_state = 38},
  [24] = {.lex_state = 38},
  [25] = {.lex_state = 38},
  [26] = {.lex_state = 38},
  [27] = {.lex_state = 38},
  [28] = {.lex_state = 38},
  [29] = {.lex_state = 38},
  [30] = {.lex_state = 38},
  [31] = {.lex_state = 38},
  [32] = {.lex_state = 39},
  [33] = {.lex_state = 39},
  [34] = {.lex_state = 38},
  [35] = {.lex_state = 39},
  [36] = {.lex_state = 38},
  [37] = {.lex_state = 38},
  [38] = {.lex_state = 38},
  [39] = {.lex_state = 38},
  [40] = {.lex_state = 38},
  [41] = {.lex_state = 38},
  [42] = {.lex_state = 38},
  [43] = {.lex_state = 38},
  [44] = {.lex_state = 38},
  [45] = {.lex_state = 38},
  [46] = {.lex_state = 38},
  [47] = {.lex_state = 38},
  [48] = {.lex_state = 38},
  [49] = {.lex_state = 38},
  [50] = {.lex_state = 38},
  [51] = {.lex_state = 38},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 38},
  [54] = {.lex_state = 38},
  [55] = {.lex_state = 38},
  [56] = {.lex_state = 38},
  [57] = {.lex_state = 38},
  [58] = {.lex_state = 38},
  [59] = {.lex_state = 38},
  [60] = {.lex_state = 38},
  [61] = {.lex_state = 38},
  [62] = {.lex_state = 38},
  [63] = {.lex_state = 39},
  [64] = {.lex_state = 39},
  [65] = {.lex_state = 39},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 8},
  [70] = {.lex_state = 41},
  [71] = {.lex_state = 40},
  [72] = {.lex_state = 40},
  [73] = {.lex_state = 41},
  [74] = {.lex_state = 41},
  [75] = {.lex_state = 40},
  [76] = {.lex_state = 38},
  [77] = {.lex_state = 8},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 5},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 40},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 40},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 40},
  [87] = {.lex_state = 41},
  [88] = {.lex_state = 41},
  [89] = {.lex_state = 41},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 9},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 9},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 36},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_run] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__int] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_scape_sequence] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_asterisk] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_format] = ACTIONS(1),
    [sym_not] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_le] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_ge] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_ne] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(115),
    [sym__pair] = STATE(118),
    [sym__if_pair] = STATE(118),
    [sym__run_pair] = STATE(118),
    [aux_sym__pair_token1] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
    [anon_sym_run] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(9), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(13), 1,
      sym_null,
    ACTIONS(15), 1,
      sym__int,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(64), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(106), 2,
      sym_expression,
      sym_delimited_expression,
    STATE(59), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [61] = 17,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(29), 1,
      sym_null,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(35), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    STATE(114), 1,
      sym_arguments,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(90), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [121] = 16,
    ACTIONS(15), 1,
      sym__int,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(37), 1,
      sym_null,
    ACTIONS(39), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(64), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(60), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [178] = 16,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(41), 1,
      sym_null,
    ACTIONS(43), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(47), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [235] = 16,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_null,
    ACTIONS(47), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(46), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [292] = 16,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      sym_null,
    ACTIONS(49), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(60), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [349] = 16,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(51), 1,
      sym_null,
    ACTIONS(53), 1,
      sym_not,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(55), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [406] = 15,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(55), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(48), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [460] = 15,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(57), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(57), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [514] = 15,
    ACTIONS(15), 1,
      sym__int,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(59), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(64), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(51), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [568] = 15,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(59), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(51), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [622] = 15,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(61), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(92), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [676] = 15,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_format,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(63), 1,
      sym_null,
    STATE(17), 1,
      sym_function_call,
    STATE(22), 1,
      sym__format_function,
    STATE(25), 1,
      sym__function,
    STATE(33), 1,
      sym__float,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(54), 7,
      sym__evaluation,
      sym__literal,
      sym_boolean,
      sym_number,
      sym_string,
      sym_context,
      sym_logical_group,
  [730] = 9,
    ACTIONS(67), 1,
      anon_sym_DOT,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym_index,
    STATE(97), 1,
      sym_property_deref,
    STATE(99), 1,
      sym__dot,
    ACTIONS(73), 2,
      sym_lt,
      sym_gt,
    STATE(16), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(65), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [769] = 8,
    ACTIONS(67), 1,
      anon_sym_DOT,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym_index,
    STATE(97), 1,
      sym_property_deref,
    STATE(99), 1,
      sym__dot,
    ACTIONS(77), 2,
      sym_lt,
      sym_gt,
    STATE(19), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(75), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [805] = 8,
    ACTIONS(67), 1,
      anon_sym_DOT,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym_index,
    STATE(97), 1,
      sym_property_deref,
    STATE(99), 1,
      sym__dot,
    ACTIONS(81), 2,
      sym_lt,
      sym_gt,
    STATE(18), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [841] = 8,
    ACTIONS(67), 1,
      anon_sym_DOT,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym_index,
    STATE(97), 1,
      sym_property_deref,
    STATE(99), 1,
      sym__dot,
    ACTIONS(85), 2,
      sym_lt,
      sym_gt,
    STATE(19), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(83), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [877] = 8,
    ACTIONS(89), 1,
      anon_sym_DOT,
    ACTIONS(92), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym_index,
    STATE(97), 1,
      sym_property_deref,
    STATE(99), 1,
      sym__dot,
    ACTIONS(95), 2,
      sym_lt,
      sym_gt,
    STATE(19), 2,
      sym_property,
      aux_sym__evaluation_repeat1,
    ACTIONS(87), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [913] = 2,
    ACTIONS(99), 2,
      sym_lt,
      sym_gt,
    ACTIONS(97), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [932] = 2,
    ACTIONS(103), 2,
      sym_lt,
      sym_gt,
    ACTIONS(101), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [951] = 2,
    ACTIONS(107), 2,
      sym_lt,
      sym_gt,
    ACTIONS(105), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [970] = 2,
    ACTIONS(111), 2,
      sym_lt,
      sym_gt,
    ACTIONS(109), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [989] = 2,
    ACTIONS(115), 2,
      sym_lt,
      sym_gt,
    ACTIONS(113), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1008] = 2,
    ACTIONS(107), 2,
      sym_lt,
      sym_gt,
    ACTIONS(105), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1027] = 2,
    ACTIONS(119), 2,
      sym_lt,
      sym_gt,
    ACTIONS(117), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1046] = 2,
    ACTIONS(123), 2,
      sym_lt,
      sym_gt,
    ACTIONS(121), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1065] = 2,
    ACTIONS(127), 2,
      sym_lt,
      sym_gt,
    ACTIONS(125), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1084] = 4,
    ACTIONS(131), 1,
      anon_sym_DOT,
    STATE(116), 1,
      sym__dot,
    ACTIONS(133), 2,
      sym_lt,
      sym_gt,
    ACTIONS(129), 10,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1107] = 2,
    ACTIONS(137), 2,
      sym_lt,
      sym_gt,
    ACTIONS(135), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1125] = 2,
    ACTIONS(141), 2,
      sym_lt,
      sym_gt,
    ACTIONS(139), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1143] = 2,
    ACTIONS(145), 2,
      sym_lt,
      sym_gt,
    ACTIONS(143), 11,
      anon_sym_RBRACE_RBRACE,
      anon_sym_e,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1161] = 3,
    ACTIONS(147), 1,
      anon_sym_e,
    ACTIONS(133), 2,
      sym_lt,
      sym_gt,
    ACTIONS(129), 10,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1181] = 2,
    ACTIONS(151), 2,
      sym_lt,
      sym_gt,
    ACTIONS(149), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1199] = 2,
    ACTIONS(155), 2,
      sym_lt,
      sym_gt,
    ACTIONS(153), 11,
      anon_sym_RBRACE_RBRACE,
      anon_sym_e,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1217] = 2,
    ACTIONS(133), 2,
      sym_lt,
      sym_gt,
    ACTIONS(129), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1235] = 2,
    ACTIONS(159), 2,
      sym_lt,
      sym_gt,
    ACTIONS(157), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1253] = 2,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(161), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1271] = 2,
    ACTIONS(167), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1288] = 2,
    ACTIONS(171), 2,
      sym_lt,
      sym_gt,
    ACTIONS(169), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1305] = 2,
    ACTIONS(175), 2,
      sym_lt,
      sym_gt,
    ACTIONS(173), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1322] = 2,
    ACTIONS(179), 2,
      sym_lt,
      sym_gt,
    ACTIONS(177), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1339] = 5,
    STATE(7), 1,
      sym_operator,
    STATE(43), 1,
      aux_sym_expression_repeat1,
    ACTIONS(181), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(186), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1362] = 5,
    ACTIONS(189), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(43), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1384] = 5,
    ACTIONS(195), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(43), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1406] = 5,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_operator,
    STATE(53), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1428] = 5,
    ACTIONS(199), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(45), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1450] = 5,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_operator,
    STATE(49), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1472] = 5,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_operator,
    STATE(43), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1494] = 4,
    ACTIONS(205), 1,
      anon_sym_DOT,
    STATE(109), 1,
      sym__dot,
    ACTIONS(133), 2,
      sym_lt,
      sym_gt,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1514] = 2,
    ACTIONS(209), 2,
      sym_lt,
      sym_gt,
    ACTIONS(207), 9,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1530] = 2,
    ACTIONS(213), 5,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_SQUOTE,
      anon_sym_LPAREN,
      sym_not,
    ACTIONS(211), 6,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__int,
      sym_identifier,
      anon_sym_format,
  [1546] = 5,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_operator,
    STATE(43), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1568] = 5,
    ACTIONS(215), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(44), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1590] = 5,
    ACTIONS(217), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(58), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1612] = 5,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_operator,
    STATE(61), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1634] = 5,
    ACTIONS(195), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(62), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1656] = 5,
    ACTIONS(215), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(43), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1678] = 5,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_operator,
    STATE(56), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1700] = 2,
    ACTIONS(223), 2,
      sym_lt,
      sym_gt,
    ACTIONS(181), 9,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1716] = 5,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_operator,
    STATE(61), 1,
      aux_sym_expression_repeat1,
    ACTIONS(183), 2,
      sym_lt,
      sym_gt,
    ACTIONS(186), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1738] = 5,
    ACTIONS(225), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(43), 1,
      aux_sym_expression_repeat1,
    ACTIONS(191), 2,
      sym_lt,
      sym_gt,
    ACTIONS(193), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1760] = 2,
    ACTIONS(145), 2,
      sym_lt,
      sym_gt,
    ACTIONS(143), 8,
      ts_builtin_sym_end,
      anon_sym_e,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1775] = 3,
    ACTIONS(147), 1,
      anon_sym_e,
    ACTIONS(133), 2,
      sym_lt,
      sym_gt,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1792] = 2,
    ACTIONS(155), 2,
      sym_lt,
      sym_gt,
    ACTIONS(153), 8,
      ts_builtin_sym_end,
      anon_sym_e,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1807] = 7,
    ACTIONS(19), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(31), 1,
      sym__int,
    ACTIONS(33), 1,
      anon_sym_DASH,
    STATE(33), 1,
      sym__float,
    STATE(36), 2,
      sym__hex,
      sym__exp,
    STATE(117), 2,
      sym_number,
      sym_string,
  [1831] = 5,
    ACTIONS(227), 1,
      anon_sym_SQUOTE,
    ACTIONS(229), 1,
      sym__format_scape,
    ACTIONS(231), 1,
      sym__format_content,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    STATE(68), 2,
      sym_format_variable,
      aux_sym_format_string_repeat1,
  [1848] = 5,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    ACTIONS(235), 1,
      anon_sym_SQUOTE,
    ACTIONS(237), 1,
      sym__format_scape,
    ACTIONS(239), 1,
      sym__format_content,
    STATE(69), 2,
      sym_format_variable,
      aux_sym_format_string_repeat1,
  [1865] = 5,
    ACTIONS(241), 1,
      anon_sym_SQUOTE,
    ACTIONS(243), 1,
      sym__format_scape,
    ACTIONS(246), 1,
      sym__format_content,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    STATE(69), 2,
      sym_format_variable,
      aux_sym_format_string_repeat1,
  [1882] = 4,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
    ACTIONS(254), 1,
      sym__ignored_bash,
    ACTIONS(256), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(73), 2,
      sym_delimited_expression,
      aux_sym__run_pair_repeat1,
  [1896] = 4,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
    ACTIONS(260), 1,
      aux_sym__pair_token2,
    ACTIONS(263), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(71), 2,
      sym_delimited_expression,
      aux_sym__pair_repeat1,
  [1910] = 4,
    ACTIONS(266), 1,
      ts_builtin_sym_end,
    ACTIONS(268), 1,
      aux_sym__pair_token2,
    ACTIONS(270), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(71), 2,
      sym_delimited_expression,
      aux_sym__pair_repeat1,
  [1924] = 4,
    ACTIONS(272), 1,
      ts_builtin_sym_end,
    ACTIONS(274), 1,
      sym__ignored_bash,
    ACTIONS(277), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(73), 2,
      sym_delimited_expression,
      aux_sym__run_pair_repeat1,
  [1938] = 3,
    ACTIONS(256), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(280), 1,
      sym__ignored_bash,
    STATE(70), 2,
      sym_delimited_expression,
      aux_sym__run_pair_repeat1,
  [1949] = 3,
    ACTIONS(270), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(282), 1,
      aux_sym__pair_token2,
    STATE(72), 2,
      sym_delimited_expression,
      aux_sym__pair_repeat1,
  [1960] = 4,
    ACTIONS(284), 1,
      anon_sym_SQUOTE,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      sym_format_string,
    STATE(101), 1,
      sym__format_arguments,
  [1973] = 2,
    ACTIONS(290), 1,
      sym__format_scape,
    ACTIONS(288), 3,
      anon_sym_SQUOTE,
      sym__format_content,
      anon_sym_LBRACE,
  [1982] = 4,
    ACTIONS(292), 1,
      anon_sym_SQUOTE,
    ACTIONS(294), 1,
      sym_string_content,
    ACTIONS(297), 1,
      sym_scape_sequence,
    STATE(78), 1,
      aux_sym_string_repeat1,
  [1995] = 4,
    ACTIONS(300), 1,
      anon_sym_SQUOTE,
    ACTIONS(302), 1,
      sym_string_content,
    ACTIONS(304), 1,
      sym_scape_sequence,
    STATE(80), 1,
      aux_sym_string_repeat1,
  [2008] = 4,
    ACTIONS(306), 1,
      anon_sym_SQUOTE,
    ACTIONS(308), 1,
      sym_string_content,
    ACTIONS(310), 1,
      sym_scape_sequence,
    STATE(78), 1,
      aux_sym_string_repeat1,
  [2021] = 2,
    ACTIONS(314), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(312), 2,
      ts_builtin_sym_end,
      aux_sym__pair_token2,
  [2029] = 3,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_arguments_repeat1,
  [2039] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(320), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_arguments_repeat1,
  [2049] = 2,
    ACTIONS(324), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(322), 2,
      ts_builtin_sym_end,
      aux_sym__pair_token2,
  [2057] = 3,
    ACTIONS(326), 1,
      anon_sym_RPAREN,
    ACTIONS(328), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_arguments_repeat1,
  [2067] = 2,
    ACTIONS(333), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(331), 2,
      ts_builtin_sym_end,
      aux_sym__pair_token2,
  [2075] = 2,
    ACTIONS(324), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(322), 2,
      ts_builtin_sym_end,
      sym__ignored_bash,
  [2083] = 2,
    ACTIONS(333), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(331), 2,
      ts_builtin_sym_end,
      sym__ignored_bash,
  [2091] = 2,
    ACTIONS(314), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(312), 2,
      ts_builtin_sym_end,
      sym__ignored_bash,
  [2099] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(335), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_arguments_repeat1,
  [2109] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(337), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_arguments_repeat1,
  [2119] = 1,
    ACTIONS(326), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2124] = 1,
    ACTIONS(339), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2129] = 2,
    ACTIONS(341), 1,
      sym__int,
    STATE(103), 1,
      sym_format_index,
  [2136] = 1,
    ACTIONS(343), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2141] = 2,
    ACTIONS(345), 1,
      sym__int,
    ACTIONS(347), 1,
      anon_sym_DASH,
  [2148] = 1,
    ACTIONS(349), 2,
      sym_asterisk,
      sym_identifier,
  [2153] = 2,
    ACTIONS(351), 1,
      anon_sym_DOT,
    STATE(107), 1,
      sym__dot,
  [2160] = 1,
    ACTIONS(353), 2,
      sym_asterisk,
      sym_identifier,
  [2165] = 2,
    ACTIONS(355), 1,
      anon_sym_DOT,
    STATE(113), 1,
      sym__dot,
  [2172] = 1,
    ACTIONS(357), 1,
      anon_sym_RPAREN,
  [2176] = 1,
    ACTIONS(359), 1,
      anon_sym_RBRACE,
  [2180] = 1,
    ACTIONS(361), 1,
      anon_sym_RBRACE,
  [2184] = 1,
    ACTIONS(363), 1,
      sym__int,
  [2188] = 1,
    ACTIONS(365), 1,
      anon_sym_COLON,
  [2192] = 1,
    ACTIONS(367), 1,
      ts_builtin_sym_end,
  [2196] = 1,
    ACTIONS(369), 1,
      sym__int,
  [2200] = 1,
    ACTIONS(371), 1,
      anon_sym_COLON,
  [2204] = 1,
    ACTIONS(373), 1,
      sym__int,
  [2208] = 1,
    ACTIONS(375), 1,
      sym__int,
  [2212] = 1,
    ACTIONS(377), 1,
      anon_sym_COLON,
  [2216] = 1,
    ACTIONS(379), 1,
      aux_sym__hex_token1,
  [2220] = 1,
    ACTIONS(381), 1,
      sym__int,
  [2224] = 1,
    ACTIONS(383), 1,
      anon_sym_RPAREN,
  [2228] = 1,
    ACTIONS(385), 1,
      ts_builtin_sym_end,
  [2232] = 1,
    ACTIONS(387), 1,
      sym__int,
  [2236] = 1,
    ACTIONS(389), 1,
      anon_sym_RBRACK,
  [2240] = 1,
    ACTIONS(391), 1,
      ts_builtin_sym_end,
  [2244] = 1,
    ACTIONS(393), 1,
      anon_sym_LPAREN,
  [2248] = 1,
    ACTIONS(395), 1,
      sym__int,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 121,
  [SMALL_STATE(5)] = 178,
  [SMALL_STATE(6)] = 235,
  [SMALL_STATE(7)] = 292,
  [SMALL_STATE(8)] = 349,
  [SMALL_STATE(9)] = 406,
  [SMALL_STATE(10)] = 460,
  [SMALL_STATE(11)] = 514,
  [SMALL_STATE(12)] = 568,
  [SMALL_STATE(13)] = 622,
  [SMALL_STATE(14)] = 676,
  [SMALL_STATE(15)] = 730,
  [SMALL_STATE(16)] = 769,
  [SMALL_STATE(17)] = 805,
  [SMALL_STATE(18)] = 841,
  [SMALL_STATE(19)] = 877,
  [SMALL_STATE(20)] = 913,
  [SMALL_STATE(21)] = 932,
  [SMALL_STATE(22)] = 951,
  [SMALL_STATE(23)] = 970,
  [SMALL_STATE(24)] = 989,
  [SMALL_STATE(25)] = 1008,
  [SMALL_STATE(26)] = 1027,
  [SMALL_STATE(27)] = 1046,
  [SMALL_STATE(28)] = 1065,
  [SMALL_STATE(29)] = 1084,
  [SMALL_STATE(30)] = 1107,
  [SMALL_STATE(31)] = 1125,
  [SMALL_STATE(32)] = 1143,
  [SMALL_STATE(33)] = 1161,
  [SMALL_STATE(34)] = 1181,
  [SMALL_STATE(35)] = 1199,
  [SMALL_STATE(36)] = 1217,
  [SMALL_STATE(37)] = 1235,
  [SMALL_STATE(38)] = 1253,
  [SMALL_STATE(39)] = 1271,
  [SMALL_STATE(40)] = 1288,
  [SMALL_STATE(41)] = 1305,
  [SMALL_STATE(42)] = 1322,
  [SMALL_STATE(43)] = 1339,
  [SMALL_STATE(44)] = 1362,
  [SMALL_STATE(45)] = 1384,
  [SMALL_STATE(46)] = 1406,
  [SMALL_STATE(47)] = 1428,
  [SMALL_STATE(48)] = 1450,
  [SMALL_STATE(49)] = 1472,
  [SMALL_STATE(50)] = 1494,
  [SMALL_STATE(51)] = 1514,
  [SMALL_STATE(52)] = 1530,
  [SMALL_STATE(53)] = 1546,
  [SMALL_STATE(54)] = 1568,
  [SMALL_STATE(55)] = 1590,
  [SMALL_STATE(56)] = 1612,
  [SMALL_STATE(57)] = 1634,
  [SMALL_STATE(58)] = 1656,
  [SMALL_STATE(59)] = 1678,
  [SMALL_STATE(60)] = 1700,
  [SMALL_STATE(61)] = 1716,
  [SMALL_STATE(62)] = 1738,
  [SMALL_STATE(63)] = 1760,
  [SMALL_STATE(64)] = 1775,
  [SMALL_STATE(65)] = 1792,
  [SMALL_STATE(66)] = 1807,
  [SMALL_STATE(67)] = 1831,
  [SMALL_STATE(68)] = 1848,
  [SMALL_STATE(69)] = 1865,
  [SMALL_STATE(70)] = 1882,
  [SMALL_STATE(71)] = 1896,
  [SMALL_STATE(72)] = 1910,
  [SMALL_STATE(73)] = 1924,
  [SMALL_STATE(74)] = 1938,
  [SMALL_STATE(75)] = 1949,
  [SMALL_STATE(76)] = 1960,
  [SMALL_STATE(77)] = 1973,
  [SMALL_STATE(78)] = 1982,
  [SMALL_STATE(79)] = 1995,
  [SMALL_STATE(80)] = 2008,
  [SMALL_STATE(81)] = 2021,
  [SMALL_STATE(82)] = 2029,
  [SMALL_STATE(83)] = 2039,
  [SMALL_STATE(84)] = 2049,
  [SMALL_STATE(85)] = 2057,
  [SMALL_STATE(86)] = 2067,
  [SMALL_STATE(87)] = 2075,
  [SMALL_STATE(88)] = 2083,
  [SMALL_STATE(89)] = 2091,
  [SMALL_STATE(90)] = 2099,
  [SMALL_STATE(91)] = 2109,
  [SMALL_STATE(92)] = 2119,
  [SMALL_STATE(93)] = 2124,
  [SMALL_STATE(94)] = 2129,
  [SMALL_STATE(95)] = 2136,
  [SMALL_STATE(96)] = 2141,
  [SMALL_STATE(97)] = 2148,
  [SMALL_STATE(98)] = 2153,
  [SMALL_STATE(99)] = 2160,
  [SMALL_STATE(100)] = 2165,
  [SMALL_STATE(101)] = 2172,
  [SMALL_STATE(102)] = 2176,
  [SMALL_STATE(103)] = 2180,
  [SMALL_STATE(104)] = 2184,
  [SMALL_STATE(105)] = 2188,
  [SMALL_STATE(106)] = 2192,
  [SMALL_STATE(107)] = 2196,
  [SMALL_STATE(108)] = 2200,
  [SMALL_STATE(109)] = 2204,
  [SMALL_STATE(110)] = 2208,
  [SMALL_STATE(111)] = 2212,
  [SMALL_STATE(112)] = 2216,
  [SMALL_STATE(113)] = 2220,
  [SMALL_STATE(114)] = 2224,
  [SMALL_STATE(115)] = 2228,
  [SMALL_STATE(116)] = 2232,
  [SMALL_STATE(117)] = 2236,
  [SMALL_STATE(118)] = 2240,
  [SMALL_STATE(119)] = 2244,
  [SMALL_STATE(120)] = 2248,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__evaluation, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__evaluation, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__evaluation, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__evaluation, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__evaluation_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__evaluation_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__evaluation_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__evaluation_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_function, 3, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__format_function, 3, 0, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 1, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 1, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function, 4, 0, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__function, 4, 0, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_function, 4, 0, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__format_function, 4, 0, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function, 3, 0, 2),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__function, 3, 0, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__hex, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_group, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_group, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_group, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_group, 4, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_group, 5, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_group, 5, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [246] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [249] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__run_pair, 3, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pair_repeat1, 2, 0, 0),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pair_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [263] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pair_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pair, 3, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__run_pair_repeat1, 2, 0, 0),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__run_pair_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [277] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__run_pair_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format_variable, 3, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_variable, 3, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [294] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [300] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [306] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimited_expression, 5, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimited_expression, 5, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_arguments, 2, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimited_expression, 3, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimited_expression, 3, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [328] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimited_expression, 4, 0, 0),
  [333] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimited_expression, 4, 0, 0),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_arguments, 1, 0, 0),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 3, 0, 0),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 2, 0, 0),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_deref, 1, 0, 0),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_index, 1, 0, 0),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__if_pair, 3, 0, 0),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [385] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gh_actions_expressions(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gh_actions_expressions",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 5,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
